language: objective-c
osx_image: xcode10.0

env:
  global:
  - PROJECT=MBSPasswordView.xcodeproj
  - IOS_FRAMEWORK_SCHEME="MBSPasswordView"
  - IOS_SDK=iphonesimulator11.2
  matrix:
  - DESTINATION="OS=11.2,name=iPhone 8"           SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"

script:
- xcodebuild -version
- xcodebuild -showsdks
- xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=YES -enableCodeCoverage YES ENABLE_TESTABILITY=YES build test
