language: objective-c
osx_image: xcode10
script:
    - xcodebuild clean test -project MBSPasswordView.xcodeproj -scheme MBSPasswordView -destination "platform=iOS Simulator,name=iPhone X,OS=10.13" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
