osx_image: xcode11
language: swift

xcode_project: MBSPasswordView.xcodeproj
before_install:
  - brew update
  - gem install slather
  - gem install danger
  - gem install danger-swiftlint

script:
  - xcodebuild test -project MBSPasswordView.xcodeproj -scheme MBSPasswordView -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.0'

after_success: slather
